config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)', locale: /pt-BR|en/ do
    devise_for :users
    root 'articles#index'
    
    resources :articles do
      # /articles/1/comments/2
      resources :comments, only: %i[create destroy]
    end
  
    resources :categories, except: [:show]
  end
end 

app/models/comment.rb
class Comment < ApplicationRecord
  # tabela comments tem o article_id
  belongs_to :article 
  # tabela comments tem o user_id
  belongs_to :user

  validates :body, presence: true
end

# 18:20

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_article

  def create
    @article.comments.create(comment_params.to_h.merge!({ user_id: current_user.id }))
    redirect_to article_path(@article), notice: t('app.create.success', model: Comment.model_name.human)
  end

  def destroy
    comment = @article.comments.find(params[:id])
    authorize comment

    comment.destroy
    redirect_to article_path(@article), notice: t('app.create.success', model: Comment.model_name.human)
  end

  private

  def comment_params
    params.require(:comment).permit(:body)
  end

  def set_article 
    @article = Article.find(params[:article_id])
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div class="card mb-2">
  <div class="card-body">
    <h5 class="card-title"><%= month_day_comma_year(comment.created_at) %></h5>
    <h6 class="card-subtitle mb-2 text-muted"><%= t 'comments.index.commenter' %> <%= comment.user.email %></h6>
    <p class="card-text"><%= comment.body %></p>
    <%= link_to t('app.button.destroy'), article_comment_path(@article, comment), class: 'btn btn-danger', 
      data: { turbo_method: :delete, turbo_confirm: t('app.message.confirm_destroy') } if policy(comment).destroy? %>
  </div>
</div>

app/views/comments/_form.html.erb
<%= simple_form_for [@article, @article.comments.build] do |f| %>
  <div class="form-inputs">
    <%= f.input :body, input_html: { rows: 10 } %>
  </div>
  <div class="form-action">
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
<% end %>